// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package nix_v10

import (
	"database/sql"
)

type DerivationOutput struct {
	Drv  int64
	ID   string
	Path string
}

type Ref struct {
	Referrer  int64
	Reference int64
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}

type ValidPath struct {
	ID               int64
	Path             string
	Hash             string
	Registrationtime int64
	Deriver          sql.NullString
	Narsize          sql.NullInt64
	Ultimate         sql.NullInt64
	Sigs             sql.NullString
	Ca               sql.NullString
}
