// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package fetcher_cache_v2

import (
	"context"
)

const queryCache = `-- name: QueryCache :many
select value, timestamp from Cache where domain = ? and key = ?
`

type QueryCacheParams struct {
	Domain string
	Key    string
}

type QueryCacheRow struct {
	Value     string
	Timestamp int64
}

func (q *Queries) QueryCache(ctx context.Context, arg QueryCacheParams) ([]QueryCacheRow, error) {
	rows, err := q.db.QueryContext(ctx, queryCache, arg.Domain, arg.Key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryCacheRow
	for rows.Next() {
		var i QueryCacheRow
		if err := rows.Scan(&i.Value, &i.Timestamp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCache = `-- name: UpsertCache :exec
insert or replace into Cache(domain, key, value, timestamp) values (?, ?, ?, ?)
`

type UpsertCacheParams struct {
	Domain    string
	Key       string
	Value     string
	Timestamp int64
}

func (q *Queries) UpsertCache(ctx context.Context, arg UpsertCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertCache,
		arg.Domain,
		arg.Key,
		arg.Value,
		arg.Timestamp,
	)
	return err
}
