// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package binary_cache_v6

import (
	"database/sql"
)

type BinaryCach struct {
	ID            int64
	Url           string
	Timestamp     int64
	Storedir      string
	Wantmassquery int64
	Priority      int64
}

type LastPurge struct {
	Dummy string
	Value sql.NullInt64
}

type NAR struct {
	Cache       int64
	Hashpart    string
	Namepart    sql.NullString
	Url         sql.NullString
	Compression sql.NullString
	Filehash    sql.NullString
	Filesize    sql.NullInt64
	Narhash     sql.NullString
	Narsize     sql.NullInt64
	Refs        sql.NullString
	Deriver     sql.NullString
	Sigs        sql.NullString
	Ca          sql.NullString
	Timestamp   int64
	Present     int64
}

type Realisation struct {
	Cache     int64
	Outputid  string
	Content   []byte
	Timestamp int64
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}
